name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # Adjust based on your .NET version

    - name: Restore dependencies
      run: dotnet restore File_Chunks.sln

    - name: Build solution
      run: dotnet build File_Chunks.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test test/File_Chunks.Tests --no-build --verbosity normal
