name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Adjust based on your .NET version

    - name: Restore dependencies
      run: dotnet restore src/File_Chunks.sln

    - name: Build solution
      run: dotnet build src/File_Chunks.sln --no-restore --configuration Release

    - name: Run tests and generate .trx
      run: dotnet test src/File_Chunks.sln --no-build --verbosity detailed --logger "trx;LogFileName=test-results.trx"

    - name: Locate and upload test results
      run: |
        echo "Searching for .trx files..."
        find . -name "*.trx" -print
      continue-on-error: false

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: "**/*.trx" # Dynamically match .trx files

